# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.abnormal_behaviour import AbnormalBehaviour
from openapi_server.models.analytics_metadata_info import AnalyticsMetadataInfo
from openapi_server.models.dispersion_info import DispersionInfo
from openapi_server.models.dn_perf_info import DnPerfInfo
from openapi_server.models.network_perf_info import NetworkPerfInfo
from openapi_server.models.nf_load_level_information import NfLoadLevelInformation
from openapi_server.models.nsi_load_level_info import NsiLoadLevelInfo
from openapi_server.models.qos_sustainability_info import QosSustainabilityInfo
from openapi_server.models.redundant_transmission_exp_info import RedundantTransmissionExpInfo
from openapi_server.models.service_experience_info import ServiceExperienceInfo
from openapi_server.models.slice_load_level_information import SliceLoadLevelInformation
from openapi_server.models.smcce_info import SmcceInfo
from openapi_server.models.ue_communication import UeCommunication
from openapi_server.models.ue_mobility import UeMobility
from openapi_server.models.user_data_congestion_info import UserDataCongestionInfo
from openapi_server.models.wlan_performance_info import WlanPerformanceInfo
import re
from openapi_server import util

from openapi_server.models.abnormal_behaviour import AbnormalBehaviour  # noqa: E501
from openapi_server.models.analytics_metadata_info import AnalyticsMetadataInfo  # noqa: E501
from openapi_server.models.dispersion_info import DispersionInfo  # noqa: E501
from openapi_server.models.dn_perf_info import DnPerfInfo  # noqa: E501
from openapi_server.models.network_perf_info import NetworkPerfInfo  # noqa: E501
from openapi_server.models.nf_load_level_information import NfLoadLevelInformation  # noqa: E501
from openapi_server.models.nsi_load_level_info import NsiLoadLevelInfo  # noqa: E501
from openapi_server.models.qos_sustainability_info import QosSustainabilityInfo  # noqa: E501
from openapi_server.models.redundant_transmission_exp_info import RedundantTransmissionExpInfo  # noqa: E501
from openapi_server.models.service_experience_info import ServiceExperienceInfo  # noqa: E501
from openapi_server.models.slice_load_level_information import SliceLoadLevelInformation  # noqa: E501
from openapi_server.models.smcce_info import SmcceInfo  # noqa: E501
from openapi_server.models.ue_communication import UeCommunication  # noqa: E501
from openapi_server.models.ue_mobility import UeMobility  # noqa: E501
from openapi_server.models.user_data_congestion_info import UserDataCongestionInfo  # noqa: E501
from openapi_server.models.wlan_performance_info import WlanPerformanceInfo  # noqa: E501
import re  # noqa: E501

class AnalyticsData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, expiry=None, time_stamp_gen=None, ana_meta_info=None, slice_load_level_infos=None, nsi_load_level_infos=None, nf_load_level_infos=None, nw_perfs=None, svc_exps=None, qos_sustain_infos=None, ue_mobs=None, ue_comms=None, user_data_cong_infos=None, abnor_behavrs=None, smcc_exps=None, disper_infos=None, red_trans_infos=None, wlan_infos=None, dn_perf_infos=None, supp_feat=None):  # noqa: E501
        """AnalyticsData - a model defined in OpenAPI

        :param start: The start of this AnalyticsData.  # noqa: E501
        :type start: datetime
        :param expiry: The expiry of this AnalyticsData.  # noqa: E501
        :type expiry: datetime
        :param time_stamp_gen: The time_stamp_gen of this AnalyticsData.  # noqa: E501
        :type time_stamp_gen: datetime
        :param ana_meta_info: The ana_meta_info of this AnalyticsData.  # noqa: E501
        :type ana_meta_info: AnalyticsMetadataInfo
        :param slice_load_level_infos: The slice_load_level_infos of this AnalyticsData.  # noqa: E501
        :type slice_load_level_infos: List[SliceLoadLevelInformation]
        :param nsi_load_level_infos: The nsi_load_level_infos of this AnalyticsData.  # noqa: E501
        :type nsi_load_level_infos: List[NsiLoadLevelInfo]
        :param nf_load_level_infos: The nf_load_level_infos of this AnalyticsData.  # noqa: E501
        :type nf_load_level_infos: List[NfLoadLevelInformation]
        :param nw_perfs: The nw_perfs of this AnalyticsData.  # noqa: E501
        :type nw_perfs: List[NetworkPerfInfo]
        :param svc_exps: The svc_exps of this AnalyticsData.  # noqa: E501
        :type svc_exps: List[ServiceExperienceInfo]
        :param qos_sustain_infos: The qos_sustain_infos of this AnalyticsData.  # noqa: E501
        :type qos_sustain_infos: List[QosSustainabilityInfo]
        :param ue_mobs: The ue_mobs of this AnalyticsData.  # noqa: E501
        :type ue_mobs: List[UeMobility]
        :param ue_comms: The ue_comms of this AnalyticsData.  # noqa: E501
        :type ue_comms: List[UeCommunication]
        :param user_data_cong_infos: The user_data_cong_infos of this AnalyticsData.  # noqa: E501
        :type user_data_cong_infos: List[UserDataCongestionInfo]
        :param abnor_behavrs: The abnor_behavrs of this AnalyticsData.  # noqa: E501
        :type abnor_behavrs: List[AbnormalBehaviour]
        :param smcc_exps: The smcc_exps of this AnalyticsData.  # noqa: E501
        :type smcc_exps: List[SmcceInfo]
        :param disper_infos: The disper_infos of this AnalyticsData.  # noqa: E501
        :type disper_infos: List[DispersionInfo]
        :param red_trans_infos: The red_trans_infos of this AnalyticsData.  # noqa: E501
        :type red_trans_infos: List[RedundantTransmissionExpInfo]
        :param wlan_infos: The wlan_infos of this AnalyticsData.  # noqa: E501
        :type wlan_infos: List[WlanPerformanceInfo]
        :param dn_perf_infos: The dn_perf_infos of this AnalyticsData.  # noqa: E501
        :type dn_perf_infos: List[DnPerfInfo]
        :param supp_feat: The supp_feat of this AnalyticsData.  # noqa: E501
        :type supp_feat: str
        """
        self.openapi_types = {
            'start': datetime,
            'expiry': datetime,
            'time_stamp_gen': datetime,
            'ana_meta_info': AnalyticsMetadataInfo,
            'slice_load_level_infos': List[SliceLoadLevelInformation],
            'nsi_load_level_infos': List[NsiLoadLevelInfo],
            'nf_load_level_infos': List[NfLoadLevelInformation],
            'nw_perfs': List[NetworkPerfInfo],
            'svc_exps': List[ServiceExperienceInfo],
            'qos_sustain_infos': List[QosSustainabilityInfo],
            'ue_mobs': List[UeMobility],
            'ue_comms': List[UeCommunication],
            'user_data_cong_infos': List[UserDataCongestionInfo],
            'abnor_behavrs': List[AbnormalBehaviour],
            'smcc_exps': List[SmcceInfo],
            'disper_infos': List[DispersionInfo],
            'red_trans_infos': List[RedundantTransmissionExpInfo],
            'wlan_infos': List[WlanPerformanceInfo],
            'dn_perf_infos': List[DnPerfInfo],
            'supp_feat': str
        }

        self.attribute_map = {
            'start': 'start',
            'expiry': 'expiry',
            'time_stamp_gen': 'timeStampGen',
            'ana_meta_info': 'anaMetaInfo',
            'slice_load_level_infos': 'sliceLoadLevelInfos',
            'nsi_load_level_infos': 'nsiLoadLevelInfos',
            'nf_load_level_infos': 'nfLoadLevelInfos',
            'nw_perfs': 'nwPerfs',
            'svc_exps': 'svcExps',
            'qos_sustain_infos': 'qosSustainInfos',
            'ue_mobs': 'ueMobs',
            'ue_comms': 'ueComms',
            'user_data_cong_infos': 'userDataCongInfos',
            'abnor_behavrs': 'abnorBehavrs',
            'smcc_exps': 'smccExps',
            'disper_infos': 'disperInfos',
            'red_trans_infos': 'redTransInfos',
            'wlan_infos': 'wlanInfos',
            'dn_perf_infos': 'dnPerfInfos',
            'supp_feat': 'suppFeat'
        }

        self.start = start
        self.expiry = expiry
        self.time_stamp_gen = time_stamp_gen
        self.ana_meta_info = ana_meta_info
        self.slice_load_level_infos = slice_load_level_infos
        self.nsi_load_level_infos = nsi_load_level_infos
        self.nf_load_level_infos = nf_load_level_infos
        self.nw_perfs = nw_perfs
        self.svc_exps = svc_exps
        self.qos_sustain_infos = qos_sustain_infos
        self.ue_mobs = ue_mobs
        self.ue_comms = ue_comms
        self.user_data_cong_infos = user_data_cong_infos
        self.abnor_behavrs = abnor_behavrs
        self.smcc_exps = smcc_exps
        self.disper_infos = disper_infos
        self.red_trans_infos = red_trans_infos
        self.wlan_infos = wlan_infos
        self.dn_perf_infos = dn_perf_infos
        self.supp_feat = supp_feat

    @classmethod
    def from_dict(cls, dikt) -> 'AnalyticsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnalyticsData of this AnalyticsData.  # noqa: E501
        :rtype: AnalyticsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self):
        """Gets the start of this AnalyticsData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The start of this AnalyticsData.
        :rtype: datetime
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this AnalyticsData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param start: The start of this AnalyticsData.
        :type start: datetime
        """

        self._start = start

    @property
    def expiry(self):
        """Gets the expiry of this AnalyticsData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The expiry of this AnalyticsData.
        :rtype: datetime
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry):
        """Sets the expiry of this AnalyticsData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param expiry: The expiry of this AnalyticsData.
        :type expiry: datetime
        """

        self._expiry = expiry

    @property
    def time_stamp_gen(self):
        """Gets the time_stamp_gen of this AnalyticsData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The time_stamp_gen of this AnalyticsData.
        :rtype: datetime
        """
        return self._time_stamp_gen

    @time_stamp_gen.setter
    def time_stamp_gen(self, time_stamp_gen):
        """Sets the time_stamp_gen of this AnalyticsData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param time_stamp_gen: The time_stamp_gen of this AnalyticsData.
        :type time_stamp_gen: datetime
        """

        self._time_stamp_gen = time_stamp_gen

    @property
    def ana_meta_info(self):
        """Gets the ana_meta_info of this AnalyticsData.


        :return: The ana_meta_info of this AnalyticsData.
        :rtype: AnalyticsMetadataInfo
        """
        return self._ana_meta_info

    @ana_meta_info.setter
    def ana_meta_info(self, ana_meta_info):
        """Sets the ana_meta_info of this AnalyticsData.


        :param ana_meta_info: The ana_meta_info of this AnalyticsData.
        :type ana_meta_info: AnalyticsMetadataInfo
        """

        self._ana_meta_info = ana_meta_info

    @property
    def slice_load_level_infos(self):
        """Gets the slice_load_level_infos of this AnalyticsData.

        The slices and their load level information.  # noqa: E501

        :return: The slice_load_level_infos of this AnalyticsData.
        :rtype: List[SliceLoadLevelInformation]
        """
        return self._slice_load_level_infos

    @slice_load_level_infos.setter
    def slice_load_level_infos(self, slice_load_level_infos):
        """Sets the slice_load_level_infos of this AnalyticsData.

        The slices and their load level information.  # noqa: E501

        :param slice_load_level_infos: The slice_load_level_infos of this AnalyticsData.
        :type slice_load_level_infos: List[SliceLoadLevelInformation]
        """
        if slice_load_level_infos is not None and len(slice_load_level_infos) < 1:
            raise ValueError("Invalid value for `slice_load_level_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._slice_load_level_infos = slice_load_level_infos

    @property
    def nsi_load_level_infos(self):
        """Gets the nsi_load_level_infos of this AnalyticsData.


        :return: The nsi_load_level_infos of this AnalyticsData.
        :rtype: List[NsiLoadLevelInfo]
        """
        return self._nsi_load_level_infos

    @nsi_load_level_infos.setter
    def nsi_load_level_infos(self, nsi_load_level_infos):
        """Sets the nsi_load_level_infos of this AnalyticsData.


        :param nsi_load_level_infos: The nsi_load_level_infos of this AnalyticsData.
        :type nsi_load_level_infos: List[NsiLoadLevelInfo]
        """
        if nsi_load_level_infos is not None and len(nsi_load_level_infos) < 1:
            raise ValueError("Invalid value for `nsi_load_level_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._nsi_load_level_infos = nsi_load_level_infos

    @property
    def nf_load_level_infos(self):
        """Gets the nf_load_level_infos of this AnalyticsData.


        :return: The nf_load_level_infos of this AnalyticsData.
        :rtype: List[NfLoadLevelInformation]
        """
        return self._nf_load_level_infos

    @nf_load_level_infos.setter
    def nf_load_level_infos(self, nf_load_level_infos):
        """Sets the nf_load_level_infos of this AnalyticsData.


        :param nf_load_level_infos: The nf_load_level_infos of this AnalyticsData.
        :type nf_load_level_infos: List[NfLoadLevelInformation]
        """
        if nf_load_level_infos is not None and len(nf_load_level_infos) < 1:
            raise ValueError("Invalid value for `nf_load_level_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._nf_load_level_infos = nf_load_level_infos

    @property
    def nw_perfs(self):
        """Gets the nw_perfs of this AnalyticsData.


        :return: The nw_perfs of this AnalyticsData.
        :rtype: List[NetworkPerfInfo]
        """
        return self._nw_perfs

    @nw_perfs.setter
    def nw_perfs(self, nw_perfs):
        """Sets the nw_perfs of this AnalyticsData.


        :param nw_perfs: The nw_perfs of this AnalyticsData.
        :type nw_perfs: List[NetworkPerfInfo]
        """
        if nw_perfs is not None and len(nw_perfs) < 1:
            raise ValueError("Invalid value for `nw_perfs`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._nw_perfs = nw_perfs

    @property
    def svc_exps(self):
        """Gets the svc_exps of this AnalyticsData.


        :return: The svc_exps of this AnalyticsData.
        :rtype: List[ServiceExperienceInfo]
        """
        return self._svc_exps

    @svc_exps.setter
    def svc_exps(self, svc_exps):
        """Sets the svc_exps of this AnalyticsData.


        :param svc_exps: The svc_exps of this AnalyticsData.
        :type svc_exps: List[ServiceExperienceInfo]
        """
        if svc_exps is not None and len(svc_exps) < 1:
            raise ValueError("Invalid value for `svc_exps`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._svc_exps = svc_exps

    @property
    def qos_sustain_infos(self):
        """Gets the qos_sustain_infos of this AnalyticsData.


        :return: The qos_sustain_infos of this AnalyticsData.
        :rtype: List[QosSustainabilityInfo]
        """
        return self._qos_sustain_infos

    @qos_sustain_infos.setter
    def qos_sustain_infos(self, qos_sustain_infos):
        """Sets the qos_sustain_infos of this AnalyticsData.


        :param qos_sustain_infos: The qos_sustain_infos of this AnalyticsData.
        :type qos_sustain_infos: List[QosSustainabilityInfo]
        """
        if qos_sustain_infos is not None and len(qos_sustain_infos) < 1:
            raise ValueError("Invalid value for `qos_sustain_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._qos_sustain_infos = qos_sustain_infos

    @property
    def ue_mobs(self):
        """Gets the ue_mobs of this AnalyticsData.


        :return: The ue_mobs of this AnalyticsData.
        :rtype: List[UeMobility]
        """
        return self._ue_mobs

    @ue_mobs.setter
    def ue_mobs(self, ue_mobs):
        """Sets the ue_mobs of this AnalyticsData.


        :param ue_mobs: The ue_mobs of this AnalyticsData.
        :type ue_mobs: List[UeMobility]
        """
        if ue_mobs is not None and len(ue_mobs) < 1:
            raise ValueError("Invalid value for `ue_mobs`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._ue_mobs = ue_mobs

    @property
    def ue_comms(self):
        """Gets the ue_comms of this AnalyticsData.


        :return: The ue_comms of this AnalyticsData.
        :rtype: List[UeCommunication]
        """
        return self._ue_comms

    @ue_comms.setter
    def ue_comms(self, ue_comms):
        """Sets the ue_comms of this AnalyticsData.


        :param ue_comms: The ue_comms of this AnalyticsData.
        :type ue_comms: List[UeCommunication]
        """
        if ue_comms is not None and len(ue_comms) < 1:
            raise ValueError("Invalid value for `ue_comms`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._ue_comms = ue_comms

    @property
    def user_data_cong_infos(self):
        """Gets the user_data_cong_infos of this AnalyticsData.


        :return: The user_data_cong_infos of this AnalyticsData.
        :rtype: List[UserDataCongestionInfo]
        """
        return self._user_data_cong_infos

    @user_data_cong_infos.setter
    def user_data_cong_infos(self, user_data_cong_infos):
        """Sets the user_data_cong_infos of this AnalyticsData.


        :param user_data_cong_infos: The user_data_cong_infos of this AnalyticsData.
        :type user_data_cong_infos: List[UserDataCongestionInfo]
        """
        if user_data_cong_infos is not None and len(user_data_cong_infos) < 1:
            raise ValueError("Invalid value for `user_data_cong_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._user_data_cong_infos = user_data_cong_infos

    @property
    def abnor_behavrs(self):
        """Gets the abnor_behavrs of this AnalyticsData.


        :return: The abnor_behavrs of this AnalyticsData.
        :rtype: List[AbnormalBehaviour]
        """
        return self._abnor_behavrs

    @abnor_behavrs.setter
    def abnor_behavrs(self, abnor_behavrs):
        """Sets the abnor_behavrs of this AnalyticsData.


        :param abnor_behavrs: The abnor_behavrs of this AnalyticsData.
        :type abnor_behavrs: List[AbnormalBehaviour]
        """
        if abnor_behavrs is not None and len(abnor_behavrs) < 1:
            raise ValueError("Invalid value for `abnor_behavrs`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._abnor_behavrs = abnor_behavrs

    @property
    def smcc_exps(self):
        """Gets the smcc_exps of this AnalyticsData.


        :return: The smcc_exps of this AnalyticsData.
        :rtype: List[SmcceInfo]
        """
        return self._smcc_exps

    @smcc_exps.setter
    def smcc_exps(self, smcc_exps):
        """Sets the smcc_exps of this AnalyticsData.


        :param smcc_exps: The smcc_exps of this AnalyticsData.
        :type smcc_exps: List[SmcceInfo]
        """
        if smcc_exps is not None and len(smcc_exps) < 1:
            raise ValueError("Invalid value for `smcc_exps`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._smcc_exps = smcc_exps

    @property
    def disper_infos(self):
        """Gets the disper_infos of this AnalyticsData.


        :return: The disper_infos of this AnalyticsData.
        :rtype: List[DispersionInfo]
        """
        return self._disper_infos

    @disper_infos.setter
    def disper_infos(self, disper_infos):
        """Sets the disper_infos of this AnalyticsData.


        :param disper_infos: The disper_infos of this AnalyticsData.
        :type disper_infos: List[DispersionInfo]
        """
        if disper_infos is not None and len(disper_infos) < 1:
            raise ValueError("Invalid value for `disper_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._disper_infos = disper_infos

    @property
    def red_trans_infos(self):
        """Gets the red_trans_infos of this AnalyticsData.


        :return: The red_trans_infos of this AnalyticsData.
        :rtype: List[RedundantTransmissionExpInfo]
        """
        return self._red_trans_infos

    @red_trans_infos.setter
    def red_trans_infos(self, red_trans_infos):
        """Sets the red_trans_infos of this AnalyticsData.


        :param red_trans_infos: The red_trans_infos of this AnalyticsData.
        :type red_trans_infos: List[RedundantTransmissionExpInfo]
        """
        if red_trans_infos is not None and len(red_trans_infos) < 1:
            raise ValueError("Invalid value for `red_trans_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._red_trans_infos = red_trans_infos

    @property
    def wlan_infos(self):
        """Gets the wlan_infos of this AnalyticsData.


        :return: The wlan_infos of this AnalyticsData.
        :rtype: List[WlanPerformanceInfo]
        """
        return self._wlan_infos

    @wlan_infos.setter
    def wlan_infos(self, wlan_infos):
        """Sets the wlan_infos of this AnalyticsData.


        :param wlan_infos: The wlan_infos of this AnalyticsData.
        :type wlan_infos: List[WlanPerformanceInfo]
        """
        if wlan_infos is not None and len(wlan_infos) < 1:
            raise ValueError("Invalid value for `wlan_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._wlan_infos = wlan_infos

    @property
    def dn_perf_infos(self):
        """Gets the dn_perf_infos of this AnalyticsData.


        :return: The dn_perf_infos of this AnalyticsData.
        :rtype: List[DnPerfInfo]
        """
        return self._dn_perf_infos

    @dn_perf_infos.setter
    def dn_perf_infos(self, dn_perf_infos):
        """Sets the dn_perf_infos of this AnalyticsData.


        :param dn_perf_infos: The dn_perf_infos of this AnalyticsData.
        :type dn_perf_infos: List[DnPerfInfo]
        """
        if dn_perf_infos is not None and len(dn_perf_infos) < 1:
            raise ValueError("Invalid value for `dn_perf_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._dn_perf_infos = dn_perf_infos

    @property
    def supp_feat(self):
        """Gets the supp_feat of this AnalyticsData.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supp_feat of this AnalyticsData.
        :rtype: str
        """
        return self._supp_feat

    @supp_feat.setter
    def supp_feat(self, supp_feat):
        """Sets the supp_feat of this AnalyticsData.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supp_feat: The supp_feat of this AnalyticsData.
        :type supp_feat: str
        """
        if supp_feat is not None and not re.search(r'^[A-Fa-f0-9]*$', supp_feat):  # noqa: E501
            raise ValueError("Invalid value for `supp_feat`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._supp_feat = supp_feat
