# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AppliedSmccTypeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DNN_CC = "DNN_CC"
    SNSSAI_CC = "SNSSAI_CC"
    def __init__(self):  # noqa: E501
        """AppliedSmccTypeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AppliedSmccTypeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppliedSmccType_anyOf of this AppliedSmccTypeAnyOf.  # noqa: E501
        :rtype: AppliedSmccTypeAnyOf
        """
        return util.deserialize_model(dikt, cls)
