# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AssociationTypeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    IMEI_CHANGE = "IMEI_CHANGE"
    IMEISV_CHANGE = "IMEISV_CHANGE"
    def __init__(self):  # noqa: E501
        """AssociationTypeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AssociationTypeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssociationType_anyOf of this AssociationTypeAnyOf.  # noqa: E501
        :rtype: AssociationTypeAnyOf
        """
        return util.deserialize_model(dikt, cls)
