# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BatteryIndication(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, battery_ind=None, replaceable_ind=None, rechargeable_ind=None):  # noqa: E501
        """BatteryIndication - a model defined in OpenAPI

        :param battery_ind: The battery_ind of this BatteryIndication.  # noqa: E501
        :type battery_ind: bool
        :param replaceable_ind: The replaceable_ind of this BatteryIndication.  # noqa: E501
        :type replaceable_ind: bool
        :param rechargeable_ind: The rechargeable_ind of this BatteryIndication.  # noqa: E501
        :type rechargeable_ind: bool
        """
        self.openapi_types = {
            'battery_ind': bool,
            'replaceable_ind': bool,
            'rechargeable_ind': bool
        }

        self.attribute_map = {
            'battery_ind': 'batteryInd',
            'replaceable_ind': 'replaceableInd',
            'rechargeable_ind': 'rechargeableInd'
        }

        self.battery_ind = battery_ind
        self.replaceable_ind = replaceable_ind
        self.rechargeable_ind = rechargeable_ind

    @classmethod
    def from_dict(cls, dikt) -> 'BatteryIndication':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatteryIndication of this BatteryIndication.  # noqa: E501
        :rtype: BatteryIndication
        """
        return util.deserialize_model(dikt, cls)

    @property
    def battery_ind(self):
        """Gets the battery_ind of this BatteryIndication.

        This IE shall indicate whether the UE is battery powered or not. true: the UE is battery powered; false or absent: the UE is not battery powered   # noqa: E501

        :return: The battery_ind of this BatteryIndication.
        :rtype: bool
        """
        return self._battery_ind

    @battery_ind.setter
    def battery_ind(self, battery_ind):
        """Sets the battery_ind of this BatteryIndication.

        This IE shall indicate whether the UE is battery powered or not. true: the UE is battery powered; false or absent: the UE is not battery powered   # noqa: E501

        :param battery_ind: The battery_ind of this BatteryIndication.
        :type battery_ind: bool
        """

        self._battery_ind = battery_ind

    @property
    def replaceable_ind(self):
        """Gets the replaceable_ind of this BatteryIndication.

        This IE shall indicate whether the battery of the UE is replaceable or not. true: the battery of the UE is replaceable; false or absent: the battery of the UE is not replaceable.   # noqa: E501

        :return: The replaceable_ind of this BatteryIndication.
        :rtype: bool
        """
        return self._replaceable_ind

    @replaceable_ind.setter
    def replaceable_ind(self, replaceable_ind):
        """Sets the replaceable_ind of this BatteryIndication.

        This IE shall indicate whether the battery of the UE is replaceable or not. true: the battery of the UE is replaceable; false or absent: the battery of the UE is not replaceable.   # noqa: E501

        :param replaceable_ind: The replaceable_ind of this BatteryIndication.
        :type replaceable_ind: bool
        """

        self._replaceable_ind = replaceable_ind

    @property
    def rechargeable_ind(self):
        """Gets the rechargeable_ind of this BatteryIndication.

        This IE shall indicate whether the battery of the UE is rechargeable or not. true: the battery of UE is rechargeable; false or absent: the battery of the UE is not rechargeable.   # noqa: E501

        :return: The rechargeable_ind of this BatteryIndication.
        :rtype: bool
        """
        return self._rechargeable_ind

    @rechargeable_ind.setter
    def rechargeable_ind(self, rechargeable_ind):
        """Sets the rechargeable_ind of this BatteryIndication.

        This IE shall indicate whether the battery of the UE is rechargeable or not. true: the battery of UE is rechargeable; false or absent: the battery of the UE is not rechargeable.   # noqa: E501

        :param rechargeable_ind: The rechargeable_ind of this BatteryIndication.
        :type rechargeable_ind: bool
        """

        self._rechargeable_ind = rechargeable_ind
