# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ChargPolicyInvocationCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, chg_ply_invocs=None):  # noqa: E501
        """ChargPolicyInvocationCollection - a model defined in OpenAPI

        :param chg_ply_invocs: The chg_ply_invocs of this ChargPolicyInvocationCollection.  # noqa: E501
        :type chg_ply_invocs: List[str]
        """
        self.openapi_types = {
            'chg_ply_invocs': List[str]
        }

        self.attribute_map = {
            'chg_ply_invocs': 'chgPlyInvocs'
        }

        self.chg_ply_invocs = chg_ply_invocs

    @classmethod
    def from_dict(cls, dikt) -> 'ChargPolicyInvocationCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChargPolicyInvocationCollection of this ChargPolicyInvocationCollection.  # noqa: E501
        :rtype: ChargPolicyInvocationCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chg_ply_invocs(self):
        """Gets the chg_ply_invocs of this ChargPolicyInvocationCollection.


        :return: The chg_ply_invocs of this ChargPolicyInvocationCollection.
        :rtype: List[str]
        """
        return self._chg_ply_invocs

    @chg_ply_invocs.setter
    def chg_ply_invocs(self, chg_ply_invocs):
        """Sets the chg_ply_invocs of this ChargPolicyInvocationCollection.


        :param chg_ply_invocs: The chg_ply_invocs of this ChargPolicyInvocationCollection.
        :type chg_ply_invocs: List[str]
        """
        if chg_ply_invocs is None:
            raise ValueError("Invalid value for `chg_ply_invocs`, must not be `None`")  # noqa: E501
        if chg_ply_invocs is not None and len(chg_ply_invocs) < 1:
            raise ValueError("Invalid value for `chg_ply_invocs`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._chg_ply_invocs = chg_ply_invocs
