# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CnTypeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SINGLE_4G = "SINGLE_4G"
    SINGLE_5G = "SINGLE_5G"
    DUAL_4G5G = "DUAL_4G5G"
    def __init__(self):  # noqa: E501
        """CnTypeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CnTypeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CnType_anyOf of this CnTypeAnyOf.  # noqa: E501
        :rtype: CnTypeAnyOf
        """
        return util.deserialize_model(dikt, cls)
