# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.notification_method1_any_of import NotificationMethod1AnyOf
from openapi_server import util

from openapi_server.models.notification_method1_any_of import NotificationMethod1AnyOf  # noqa: E501

class NotificationMethod1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """NotificationMethod1 - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationMethod1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationMethod_1 of this NotificationMethod1.  # noqa: E501
        :rtype: NotificationMethod1
        """
        return util.deserialize_model(dikt, cls)
