# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NwdafFailureCodeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNAVAILABLE_DATA = "UNAVAILABLE_DATA"
    BOTH_STAT_PRED_NOT_ALLOWED = "BOTH_STAT_PRED_NOT_ALLOWED"
    UNSATISFIED_REQUESTED_ANALYTICS_TIME = "UNSATISFIED_REQUESTED_ANALYTICS_TIME"
    OTHER = "OTHER"
    def __init__(self):  # noqa: E501
        """NwdafFailureCodeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NwdafFailureCodeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NwdafFailureCode_anyOf of this NwdafFailureCodeAnyOf.  # noqa: E501
        :rtype: NwdafFailureCodeAnyOf
        """
        return util.deserialize_model(dikt, cls)
