# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.addr_fqdn import AddrFqdn
from openapi_server.models.flow_info import FlowInfo
from openapi_server.models.ip_addr import IpAddr
from openapi_server.models.performance_data import PerformanceData
from openapi_server.models.user_location import UserLocation
from openapi_server import util

from openapi_server.models.addr_fqdn import AddrFqdn  # noqa: E501
from openapi_server.models.flow_info import FlowInfo  # noqa: E501
from openapi_server.models.ip_addr import IpAddr  # noqa: E501
from openapi_server.models.performance_data import PerformanceData  # noqa: E501
from openapi_server.models.user_location import UserLocation  # noqa: E501

class PerformanceDataInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app_id=None, ue_ip_addr=None, ip_traffic_filter=None, user_loc=None, app_locs=None, as_addr=None, perf_data=None, time_stamp=None):  # noqa: E501
        """PerformanceDataInfo - a model defined in OpenAPI

        :param app_id: The app_id of this PerformanceDataInfo.  # noqa: E501
        :type app_id: str
        :param ue_ip_addr: The ue_ip_addr of this PerformanceDataInfo.  # noqa: E501
        :type ue_ip_addr: IpAddr
        :param ip_traffic_filter: The ip_traffic_filter of this PerformanceDataInfo.  # noqa: E501
        :type ip_traffic_filter: FlowInfo
        :param user_loc: The user_loc of this PerformanceDataInfo.  # noqa: E501
        :type user_loc: UserLocation
        :param app_locs: The app_locs of this PerformanceDataInfo.  # noqa: E501
        :type app_locs: List[str]
        :param as_addr: The as_addr of this PerformanceDataInfo.  # noqa: E501
        :type as_addr: AddrFqdn
        :param perf_data: The perf_data of this PerformanceDataInfo.  # noqa: E501
        :type perf_data: PerformanceData
        :param time_stamp: The time_stamp of this PerformanceDataInfo.  # noqa: E501
        :type time_stamp: datetime
        """
        self.openapi_types = {
            'app_id': str,
            'ue_ip_addr': IpAddr,
            'ip_traffic_filter': FlowInfo,
            'user_loc': UserLocation,
            'app_locs': List[str],
            'as_addr': AddrFqdn,
            'perf_data': PerformanceData,
            'time_stamp': datetime
        }

        self.attribute_map = {
            'app_id': 'appId',
            'ue_ip_addr': 'ueIpAddr',
            'ip_traffic_filter': 'ipTrafficFilter',
            'user_loc': 'userLoc',
            'app_locs': 'appLocs',
            'as_addr': 'asAddr',
            'perf_data': 'perfData',
            'time_stamp': 'timeStamp'
        }

        self.app_id = app_id
        self.ue_ip_addr = ue_ip_addr
        self.ip_traffic_filter = ip_traffic_filter
        self.user_loc = user_loc
        self.app_locs = app_locs
        self.as_addr = as_addr
        self.perf_data = perf_data
        self.time_stamp = time_stamp

    @classmethod
    def from_dict(cls, dikt) -> 'PerformanceDataInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PerformanceDataInfo of this PerformanceDataInfo.  # noqa: E501
        :rtype: PerformanceDataInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_id(self):
        """Gets the app_id of this PerformanceDataInfo.

        String providing an application identifier.  # noqa: E501

        :return: The app_id of this PerformanceDataInfo.
        :rtype: str
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id):
        """Sets the app_id of this PerformanceDataInfo.

        String providing an application identifier.  # noqa: E501

        :param app_id: The app_id of this PerformanceDataInfo.
        :type app_id: str
        """

        self._app_id = app_id

    @property
    def ue_ip_addr(self):
        """Gets the ue_ip_addr of this PerformanceDataInfo.


        :return: The ue_ip_addr of this PerformanceDataInfo.
        :rtype: IpAddr
        """
        return self._ue_ip_addr

    @ue_ip_addr.setter
    def ue_ip_addr(self, ue_ip_addr):
        """Sets the ue_ip_addr of this PerformanceDataInfo.


        :param ue_ip_addr: The ue_ip_addr of this PerformanceDataInfo.
        :type ue_ip_addr: IpAddr
        """

        self._ue_ip_addr = ue_ip_addr

    @property
    def ip_traffic_filter(self):
        """Gets the ip_traffic_filter of this PerformanceDataInfo.


        :return: The ip_traffic_filter of this PerformanceDataInfo.
        :rtype: FlowInfo
        """
        return self._ip_traffic_filter

    @ip_traffic_filter.setter
    def ip_traffic_filter(self, ip_traffic_filter):
        """Sets the ip_traffic_filter of this PerformanceDataInfo.


        :param ip_traffic_filter: The ip_traffic_filter of this PerformanceDataInfo.
        :type ip_traffic_filter: FlowInfo
        """

        self._ip_traffic_filter = ip_traffic_filter

    @property
    def user_loc(self):
        """Gets the user_loc of this PerformanceDataInfo.


        :return: The user_loc of this PerformanceDataInfo.
        :rtype: UserLocation
        """
        return self._user_loc

    @user_loc.setter
    def user_loc(self, user_loc):
        """Sets the user_loc of this PerformanceDataInfo.


        :param user_loc: The user_loc of this PerformanceDataInfo.
        :type user_loc: UserLocation
        """

        self._user_loc = user_loc

    @property
    def app_locs(self):
        """Gets the app_locs of this PerformanceDataInfo.


        :return: The app_locs of this PerformanceDataInfo.
        :rtype: List[str]
        """
        return self._app_locs

    @app_locs.setter
    def app_locs(self, app_locs):
        """Sets the app_locs of this PerformanceDataInfo.


        :param app_locs: The app_locs of this PerformanceDataInfo.
        :type app_locs: List[str]
        """
        if app_locs is not None and len(app_locs) < 1:
            raise ValueError("Invalid value for `app_locs`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._app_locs = app_locs

    @property
    def as_addr(self):
        """Gets the as_addr of this PerformanceDataInfo.


        :return: The as_addr of this PerformanceDataInfo.
        :rtype: AddrFqdn
        """
        return self._as_addr

    @as_addr.setter
    def as_addr(self, as_addr):
        """Sets the as_addr of this PerformanceDataInfo.


        :param as_addr: The as_addr of this PerformanceDataInfo.
        :type as_addr: AddrFqdn
        """

        self._as_addr = as_addr

    @property
    def perf_data(self):
        """Gets the perf_data of this PerformanceDataInfo.


        :return: The perf_data of this PerformanceDataInfo.
        :rtype: PerformanceData
        """
        return self._perf_data

    @perf_data.setter
    def perf_data(self, perf_data):
        """Sets the perf_data of this PerformanceDataInfo.


        :param perf_data: The perf_data of this PerformanceDataInfo.
        :type perf_data: PerformanceData
        """
        if perf_data is None:
            raise ValueError("Invalid value for `perf_data`, must not be `None`")  # noqa: E501

        self._perf_data = perf_data

    @property
    def time_stamp(self):
        """Gets the time_stamp of this PerformanceDataInfo.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The time_stamp of this PerformanceDataInfo.
        :rtype: datetime
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this PerformanceDataInfo.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param time_stamp: The time_stamp of this PerformanceDataInfo.
        :type time_stamp: datetime
        """
        if time_stamp is None:
            raise ValueError("Invalid value for `time_stamp`, must not be `None`")  # noqa: E501

        self._time_stamp = time_stamp
