# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ReachabilityFilterAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    REACHABILITY_STATUS_CHANGE = "UE_REACHABILITY_STATUS_CHANGE"
    REACHABLE_DL_TRAFFIC = "UE_REACHABLE_DL_TRAFFIC"
    def __init__(self):  # noqa: E501
        """ReachabilityFilterAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ReachabilityFilterAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReachabilityFilter_anyOf of this ReachabilityFilterAnyOf.  # noqa: E501
        :rtype: ReachabilityFilterAnyOf
        """
        return util.deserialize_model(dikt, cls)
