# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TransportProtocolAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UDP = "UDP"
    TCP = "TCP"
    def __init__(self):  # noqa: E501
        """TransportProtocolAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TransportProtocolAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransportProtocol_anyOf of this TransportProtocolAnyOf.  # noqa: E501
        :rtype: TransportProtocolAnyOf
        """
        return util.deserialize_model(dikt, cls)
