# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.addr_fqdn import AddrFqdn
from openapi_server import util

from openapi_server.models.addr_fqdn import AddrFqdn  # noqa: E501

class UpfInformation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, upf_id=None, upf_addr=None):  # noqa: E501
        """UpfInformation - a model defined in OpenAPI

        :param upf_id: The upf_id of this UpfInformation.  # noqa: E501
        :type upf_id: str
        :param upf_addr: The upf_addr of this UpfInformation.  # noqa: E501
        :type upf_addr: AddrFqdn
        """
        self.openapi_types = {
            'upf_id': str,
            'upf_addr': AddrFqdn
        }

        self.attribute_map = {
            'upf_id': 'upfId',
            'upf_addr': 'upfAddr'
        }

        self.upf_id = upf_id
        self.upf_addr = upf_addr

    @classmethod
    def from_dict(cls, dikt) -> 'UpfInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpfInformation of this UpfInformation.  # noqa: E501
        :rtype: UpfInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def upf_id(self):
        """Gets the upf_id of this UpfInformation.


        :return: The upf_id of this UpfInformation.
        :rtype: str
        """
        return self._upf_id

    @upf_id.setter
    def upf_id(self, upf_id):
        """Sets the upf_id of this UpfInformation.


        :param upf_id: The upf_id of this UpfInformation.
        :type upf_id: str
        """

        self._upf_id = upf_id

    @property
    def upf_addr(self):
        """Gets the upf_addr of this UpfInformation.


        :return: The upf_addr of this UpfInformation.
        :rtype: AddrFqdn
        """
        return self._upf_addr

    @upf_addr.setter
    def upf_addr(self, upf_addr):
        """Sets the upf_addr of this UpfInformation.


        :param upf_addr: The upf_addr of this UpfInformation.
        :type upf_addr: AddrFqdn
        """

        self._upf_addr = upf_addr
