# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DnPerfOrderingCriterionAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AVERAGE_TRAFFIC_RATE = "AVERAGE_TRAFFIC_RATE"
    MAXIMUM_TRAFFIC_RATE = "MAXIMUM_TRAFFIC_RATE"
    AVERAGE_PACKET_DELAY = "AVERAGE_PACKET_DELAY"
    MAXIMUM_PACKET_DELAY = "MAXIMUM_PACKET_DELAY"
    AVERAGE_PACKET_LOSS_RATE = "AVERAGE_PACKET_LOSS_RATE"
    def __init__(self):  # noqa: E501
        """DnPerfOrderingCriterionAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DnPerfOrderingCriterionAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DnPerfOrderingCriterion_anyOf of this DnPerfOrderingCriterionAnyOf.  # noqa: E501
        :rtype: DnPerfOrderingCriterionAnyOf
        """
        return util.deserialize_model(dikt, cls)
