# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class FailureCodeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNAVAILABLE_ML_MODEL = "UNAVAILABLE_ML_MODEL"
    def __init__(self):  # noqa: E501
        """FailureCodeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'FailureCodeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FailureCode_anyOf of this FailureCodeAnyOf.  # noqa: E501
        :rtype: FailureCodeAnyOf
        """
        return util.deserialize_model(dikt, cls)
