# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NotificationMethodAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PERIODIC = "PERIODIC"
    ONE_TIME = "ONE_TIME"
    ON_EVENT_DETECTION = "ON_EVENT_DETECTION"
    def __init__(self):  # noqa: E501
        """NotificationMethodAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationMethodAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationMethod_anyOf of this NotificationMethodAnyOf.  # noqa: E501
        :rtype: NotificationMethodAnyOf
        """
        return util.deserialize_model(dikt, cls)
