# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.geographical_coordinates import GeographicalCoordinates
from openapi_server import util

from openapi_server.models.geographical_coordinates import GeographicalCoordinates  # noqa: E501

class PointAltitudeAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, point=None, altitude=None):  # noqa: E501
        """PointAltitudeAllOf - a model defined in OpenAPI

        :param point: The point of this PointAltitudeAllOf.  # noqa: E501
        :type point: GeographicalCoordinates
        :param altitude: The altitude of this PointAltitudeAllOf.  # noqa: E501
        :type altitude: float
        """
        self.openapi_types = {
            'point': GeographicalCoordinates,
            'altitude': float
        }

        self.attribute_map = {
            'point': 'point',
            'altitude': 'altitude'
        }

        self.point = point
        self.altitude = altitude

    @classmethod
    def from_dict(cls, dikt) -> 'PointAltitudeAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PointAltitude_allOf of this PointAltitudeAllOf.  # noqa: E501
        :rtype: PointAltitudeAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def point(self):
        """Gets the point of this PointAltitudeAllOf.


        :return: The point of this PointAltitudeAllOf.
        :rtype: GeographicalCoordinates
        """
        return self._point

    @point.setter
    def point(self, point):
        """Sets the point of this PointAltitudeAllOf.


        :param point: The point of this PointAltitudeAllOf.
        :type point: GeographicalCoordinates
        """
        if point is None:
            raise ValueError("Invalid value for `point`, must not be `None`")  # noqa: E501

        self._point = point

    @property
    def altitude(self):
        """Gets the altitude of this PointAltitudeAllOf.

        Indicates value of altitude.  # noqa: E501

        :return: The altitude of this PointAltitudeAllOf.
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude):
        """Sets the altitude of this PointAltitudeAllOf.

        Indicates value of altitude.  # noqa: E501

        :param altitude: The altitude of this PointAltitudeAllOf.
        :type altitude: float
        """
        if altitude is None:
            raise ValueError("Invalid value for `altitude`, must not be `None`")  # noqa: E501
        if altitude is not None and altitude > 32767:  # noqa: E501
            raise ValueError("Invalid value for `altitude`, must be a value less than or equal to `32767`")  # noqa: E501
        if altitude is not None and altitude < -32767:  # noqa: E501
            raise ValueError("Invalid value for `altitude`, must be a value greater than or equal to `-32767`")  # noqa: E501

        self._altitude = altitude
