# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ScheduledCommunicationTypeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DOWNLINK_ONLY = "DOWNLINK_ONLY"
    UPLINK_ONLY = "UPLINK_ONLY"
    BIDIRECTIONAL = "BIDIRECTIONAL"
    def __init__(self):  # noqa: E501
        """ScheduledCommunicationTypeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ScheduledCommunicationTypeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScheduledCommunicationType_anyOf of this ScheduledCommunicationTypeAnyOf.  # noqa: E501
        :rtype: ScheduledCommunicationTypeAnyOf
        """
        return util.deserialize_model(dikt, cls)
