/*
 * NSSF
 *
 * Network Slice Selection Function
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"

	"github.com/free5gc/nssf/logger"
	"github.com/free5gc/nssf/service"
	"github.com/free5gc/version"
)

var NSSF = &service.NSSF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "nssf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("NSSF version: ", version.GetVersion())
	app.Usage = "-free5gccfg common configuration file -nssfcfg nssf configuration file"
	app.Action = action
	app.Flags = NSSF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		appLog.Errorf("NSSF Run Error: %v", err)
	}
}

func action(c *cli.Context) error {
	if err := NSSF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("Failed to initialize !!")
	}

	NSSF.Start()

	return nil
}
